version: "3"

services:
  router-storage:
    image: redis:3.2-alpine
    networks:
      - router-management
    deploy:
      mode: replicated
      replicas: 1

  router-backend:
    image: tpbowden/swarm-ingress-router
    command: -r router-storage:6379 collector
    networks:
      - router-management
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  router:
    image: tpbowden/swarm-ingress-router
    command: -r router-storage:6379 server -b 0.0.0.0
    ports:
      - 80:8080
      - 443:8443
    networks:
      - router-management
      - frontends
    deploy:
      mode: global

networks:
  router-management:
  frontends:
